name: Pipeline 2 - Testes de Integração

on:
  workflow_run:
    workflows: ["Pipeline 1 - Testes Unitários"]
    types:
      - completed
  workflow_dispatch:   # <-- Permite rodar manualmente

jobs:
  integration_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-swagger-ui flask-jwt-extended requests

      - name: Run integration tests
        run: |
          echo "Aqui você rodaria seus testes de integração"
